#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent


# retrieve json data
data = json.load(sys.stdin)
port = data['sftp_tcp_port']
sftpgo_service = data['sftpgo_service']



#  test if the port is the same and if the port is opened in the FW
if str(port) == os.environ.get('SFTP_TCP_PORT',"") and str(sftpgo_service) == os.environ.get('SFTPGO_SERVICE',""):
    sys.exit(0)

try:
    # first remove the previous port set
    if os.getenv('SFTP_TCP_PORT'):
        agent.remove_public_service(os.environ['MODULE_ID'])
except:
    pass

if sftpgo_service:
    # add the new port
    agent.add_public_service(os.environ['MODULE_ID'], [
        str(port) + "/tcp", # external sftp port
    ])

# Ignore exit code
