#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent


# retrieve json data
data = json.load(sys.stdin)
port = data['sftp_tcp_port']
sftpgo_service = data['sftpgo_service']

# exit if sftpgo is not enabled
if not sftpgo_service:
    sys.exit(0)

#  test if the port is the same
if str(port) == os.environ.get('SFTP_TCP_PORT',""):
    sys.exit(0)

# first remove the previous port set
if os.getenv('SFTP_TCP_PORT'):
    agent.remove_public_service(os.environ['MODULE_ID'])

# add the new port
agent.add_public_service(os.environ['MODULE_ID'], [
    str(port) + "/tcp", # external sftp port
])

# Ignore exit code
