#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#


import os
import agent

agent.run_helper("systemctl", "--user", "enable","--now", "webserver.service").check_returncode()
agent.run_helper("systemctl", "--user", "restart", "webserver.service").check_returncode()

sftpgo_service = os.environ.get('SFTPGO_SERVICE', False) == "True"
if sftpgo_service:
    agent.run_helper("systemctl", "--user", "enable","--now", "sftpgo.service").check_returncode()
    agent.run_helper("systemctl", "--user", "restart", "sftpgo.service").check_returncode()
else:
    agent.run_helper("systemctl", "--user", "disable","--now", "sftpgo.service").check_returncode()
