#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#


import os
import agent

agent.run_helper("systemctl", "--user", "enable","--now", "webserver.service")
agent.run_helper("systemctl", "--user", "restart", "webserver.service")

sftpgo_service = os.environ.get('SFTPGO_SERVICE', False)
if sftpgo_service:
    agent.run_helper("systemctl", "--user", "enable","--now", "sftpgo.service")
    agent.run_helper("systemctl", "--user", "restart", "sftpgo.service")
else:
    agent.run_helper("systemctl", "--user", "disable","--now", "sftpgo.service")
