#!/usr/bin/env python3
#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#
import os
import json
import sys
import glob

data = json.load(sys.stdin)

port = data.get('port')
PhpVersion = data.get("PhpVersion")

#Remove php-fpm customisation, we need to be sure the container has created the php-fpm folder
files = glob.glob("php*-fpm-custom.d/dyn-"+str(port)+".custom")
for file in files:
    os.rename(file,"php"+str(PhpVersion)+"-fpm-custom.d/dyn-"+str(port)+".custom")
