#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Configure sftpgo and nginx env
# Input example:
#

import os
import json
import sys
# agent is a NethServer library which provides function to communicate with the agent
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# sftp uses the first one, sftpgo uses the second random port, nginx the third one
env_tcp_ports = os.environ["TCP_PORTS"].split(',')
sftp_tcp_port = env_tcp_ports[0]
sftpgo_tcp_port = env_tcp_ports[1]
nginx_tcp_port = env_tcp_ports[2]
# Talk with agent using file descriptor.
# Setup configuration from user input.
agent.set_env("SFTP_TCP_PORT", sftp_tcp_port)
agent.set_env("SFTPGO_TCP_PORT", sftpgo_tcp_port)
agent.set_env("NGINX_TCP_PORT", nginx_tcp_port)

# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()