#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import glob
import configparser
import json
import sys
import agent
import agent.tasks

# Find default traefik instance for current node
default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

path="databases/vhosts/*"
for file in glob.iglob(path, recursive=True):
    config = configparser.ConfigParser()
    config.read(file)
    ServerNames = config['vhost']['ServerNames'].split(',')
    for host in ServerNames:
        # remove traefik virtual host
        response = agent.tasks.run(
            agent_id=default_traefik_id,
            action='delete-route',
            data={
                'instance': os.environ['MODULE_ID'] + '-' + host
            },
        )

        # Check if traefik configuration has been successfull
        agent.assert_exp(response['exit_code'] == 0)

