#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent

# remove the port set
if os.getenv('SFTP_TCP_PORT'):
    agent.remove_public_service(os.environ['MODULE_ID'])
