#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import glob
import configparser
import json
import sys

configuration = {}

for file in glob.iglob("databases/vhosts/*.ini"):
    config = configparser.ConfigParser()
    config.read(file)
    ServerNames = config['vhost']['ServerNames'].split(',')
    vhost = {
        "ServerNames" : ServerNames,
        "Port" : int(config['vhost']['port']),
        "PhpVersion" : config['vhost']['PhpVersion'],
        "memorylimit" : int(config['vhost']['memorylimit']),
        "allowurlfopen" : config['vhost']['allowurlfopen'],
        "uploadmaxfilesize" : int(config['vhost']['uploadmaxfilesize']),
        "postmaxsize" : int(config['vhost']['postmaxsize']),
        "maxexecutiontime" : int(config['vhost']['maxexecutiontime']),
        "maxfileuploads" : int(config['vhost']['maxfileuploads'])
        }

    configuration[config['vhost']['port']] = vhost

json.dump(configuration, fp=sys.stdout)
