#!/usr/bin/env python3

import os
import shutil
import json
import sys
import subprocess


# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

ServerNames = data.get("ServerNames")
MODULE_ID = os.environ["MODULE_ID"]

# remove the database configuration
path = 'databases/vhosts/' + ServerNames[0] +'.ini'
if os.path.exists(path):
    os.remove(path)

# we need to remove the webroot folder for the website
subprocess.run(["podman","exec","-i","nginx","rm","-rf","/usr/share/nginx/html/"+ServerNames[0]])
