#!/usr/bin/env python3
#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#
import configparser
import os
import json
import sys
import subprocess

# agent is a NethServer library which provides function to communicate with the agent
import agent

config = configparser.ConfigParser()
# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

ServerNames = data.get("ServerNames")
PhpVersion = data.get("PhpVersion")
MemoryLimit = data.get("MemoryLimit",'512')
AllowUrlfOpen = data.get("AllowUrlfOpen",'enabled')
UploadMaxFilesize = data.get("UploadMaxFilesize",'4')
PostMaxSize = data.get("PostMaxSize",'8')
MaxExecutionTime = data.get("MaxExecutionTime",'0')
MaxFileUploads = data.get("MaxFileUploads",'20')

with open("databases/NextFpmPort", "r+") as fp:
    NextFpmPort = int(fp.read() or "9000") + 1
    fp.seek(0)
    fp.write(str(NextFpmPort))

config['vhost'] = {}
config['vhost']['ServerNames'] = ','.join(ServerNames)
config['vhost']['port'] = str(NextFpmPort)
config['vhost']['PhpVersion'] = str(PhpVersion)
config['vhost']['MemoryLimit'] = str(MemoryLimit)
config['vhost']['AllowUrlfOpen'] = AllowUrlfOpen
config['vhost']['UploadMaxFilesize'] = str(UploadMaxFilesize)
config['vhost']['PostMaxSize'] = str(PostMaxSize)
config['vhost']['MaxExecutionTime'] = str(MaxExecutionTime)
config['vhost']['MaxFileUploads'] = str(MaxFileUploads)

with open( 'databases/vhosts/' + str(NextFpmPort)+'.ini', 'w') as configfile:
    config.write(configfile)

# we need to create the webroot folder for the website
subprocess.run(["podman","exec","-i","nginx","mkdir","-p","/usr/share/nginx/html/"+str(NextFpmPort)])
