#!/usr/bin/env python3
#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#
import os
import json
import sys
import subprocess

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

PhpVersion = data.get("PhpVersion")

# if the phpversion exists we download and install the container
if PhpVersion:
    # build the configuration folder
    os.makedirs('php'+str(PhpVersion)+'-fpm-custom.d', exist_ok=True)
    # expand configuration
    subprocess.run(["systemctl", "--user", "reload", "nginx.service"])
    # pull the image if missing
    subprocess.run(["download-php-fpm",str(PhpVersion)])
    # start the container  if stopped
    subprocess.run(["systemctl", "--user", "enable", "--now", "phpfpm@"+str(PhpVersion)+".service"])
    # we need to reload the php fpm service to let him know about the new configuration
    subprocess.run(["systemctl", "--user", "reload", "phpfpm@"+str(PhpVersion)+".service"])
else:
    subprocess.run(["systemctl", "--user", "reload", "nginx.service"])

